@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.section .rodata
	.align	2
.LC0:
	.word	CurrentButtonState
	.align	2
.LC1:
	.word	PreviousButtonState
.text
	.align	2
	.globl	Controls_Init
	.type	 Controls_Init,function
	.thumb_func
Controls_Init:
	push	{r7, lr}
	mov	r7, sp
	ldr	r0, .L3
	mov	r1, #0
	strh	r1, [r0]
	ldr	r0, .L3+4
	mov	r1, #0
	strh	r1, [r0]
.L2:
	pop	{r7}
	pop	{r0}
	bx	r0
.L4:
	.align	2
.L3:
	.word	CurrentButtonState
	.word	PreviousButtonState
.Lfe1:
	.size	 Controls_Init,.Lfe1-Controls_Init
	.section .rodata
	.align	2
.LC2:
	.word	PreviousButtonState
	.align	2
.LC3:
	.word	CurrentButtonState
.text
	.align	2
	.globl	Controls_Process
	.type	 Controls_Process,function
	.thumb_func
Controls_Process:
	push	{r7, lr}
	mov	r7, sp
	ldr	r0, .L7
	ldr	r1, .L7+4
	ldrh	r2, [r1]
	strh	r2, [r0]
	ldr	r0, .L7+4
	mov	r1, #0
	ldr	r2, .L7+8
	ldrh	r3, [r2]
	cmp	r3, #0
	bne	.L6	@cond_branch
	mov	r1, #1
.L6:
	strh	r1, [r0]
	ldr	r0, .L7+8
	ldr	r2, .L7+12
	add	r1, r2, #0
	strh	r1, [r0]
.L5:
	pop	{r7}
	pop	{r0}
	bx	r0
.L8:
	.align	2
.L7:
	.word	PreviousButtonState
	.word	CurrentButtonState
	.word	67109168
	.word	65535
.Lfe2:
	.size	 Controls_Process,.Lfe2-Controls_Process
	.section .rodata
	.align	2
.LC4:
	.word	CurrentButtonState
.text
	.align	2
	.globl	Controls_IsButtonPressed
	.type	 Controls_IsButtonPressed,function
	.thumb_func
Controls_IsButtonPressed:
	push	{r4, r7, lr}
	add	sp, sp, #-4
	mov	r7, sp
	str	r0, [r7]
	mov	r0, #0
	ldr	r2, .L11
	ldrh	r1, [r2]
	ldr	r3, [r7]
	add	r2, r3, #0
	lsl	r3, r2, #24
	lsr	r2, r3, #24
	mov	r3, #1
	add	r4, r3, #0
	lsl	r4, r4, r2
	add	r2, r4, #0
	and	r1, r1, r2
	cmp	r1, #0
	ble	.L10	@cond_branch
	mov	r0, #1
.L10:
	b	.L9
.L12:
	.align	2
.L11:
	.word	CurrentButtonState
.L9:
	add	sp, sp, #4
	pop	{r4, r7}
	pop	{r1}
	bx	r1
.Lfe3:
	.size	 Controls_IsButtonPressed,.Lfe3-Controls_IsButtonPressed
	.section .rodata
	.align	2
.LC5:
	.word	CurrentButtonState
	.align	2
.LC6:
	.word	PreviousButtonState
.text
	.align	2
	.globl	Controls_IsButtonPressedDB
	.type	 Controls_IsButtonPressedDB,function
	.thumb_func
Controls_IsButtonPressedDB:
	push	{r7, lr}
	add	sp, sp, #-8
	mov	r7, sp
	str	r0, [r7]
	add	r0, r7, #4
	ldr	r1, [r7]
	add	r2, r1, #0
	strb	r2, [r0]
	mov	r0, #0
	ldr	r2, .L15
	ldrh	r1, [r2]
	add	r2, r7, #4
	ldrb	r3, [r2]
	asr	r1, r1, r3
	add	r2, r1, #0
	mov	r3, #1
	add	r1, r2, #0
	and	r1, r1, r3
	add	r3, r1, #0
	lsl	r2, r3, #24
	asr	r1, r2, #24
	cmp	r1, #0
	beq	.L14	@cond_branch
	ldr	r2, .L15+4
	ldrh	r1, [r2]
	add	r2, r7, #4
	ldrb	r3, [r2]
	asr	r1, r1, r3
	mov	r2, #1
	and	r1, r1, r2
	cmp	r1, #0
	bne	.L14	@cond_branch
	mov	r0, #1
.L14:
	b	.L13
.L16:
	.align	2
.L15:
	.word	CurrentButtonState
	.word	PreviousButtonState
.L13:
	add	sp, sp, #8
	pop	{r7}
	pop	{r1}
	bx	r1
.Lfe4:
	.size	 Controls_IsButtonPressedDB,.Lfe4-Controls_IsButtonPressedDB
	.comm	CurrentButtonState, 4	@ 2
	.comm	PreviousButtonState, 4	@ 2
