_AGBDIR = C:\Progra~1\agb\
.SFILES	=	start.s
.CFILES	=	basis.c car.c Controls.c Dakar.c Debug.c fixed.c Globals.c Graphics.c Sound.c
.OFILES	=	$(.SFILES:.s=.o) $(.CFILES:.c=.o)
.AFILES	=
ASFLAGS	=	-I$(_AGBDIR)/include -mthumb-interwork
CFLAGS	=	-g -O2 -I$(_AGBDIR)/include -mthumb-interwork \
		-nostdlib -Wall # -save-temps

LDFLAGS	 +=	-Map $(MAPFILE) -nostartfiles \
		-Ttext 0x08000000 -Tbss 0x03000000 \
		-L$(_AGBDIR)/lib/ -lisagbprn -lagbsyscall \
		-Tlnkscript 
DEPENDFILE	=	Makedepend
MAPFILE		=	DakarAGB.map
TARGET_ELF	=	DakarAGB.elf
TARGET_BIN	=	DakarAGB.bin

$(TARGET_BIN): $(TARGET_ELF)
	objcopy -v -O binary $< $@

$(TARGET_ELF): $(.OFILES) Makefile $(.AFILES) $(DEPENDFILE)
	@echo > $(MAPFILE)
	$(CC) -g -o $@ $(.OFILES) -Wl,$(LDFLAGS)

.PHONY: all clean depend data

all:	clean depend data $(TARGET_BIN)

clean:
	-rm $(.OFILES) $(DEPENDFILE)
clean_data:
	$(foreach .ADIR_TMP, $(dir $(.AFILES)), make -C $(.ADIR_TMP) clean;)

depend:
	$(CC) $(CFLAGS) -M $(.CFILES) > $(DEPENDFILE)

$(DEPENDFILE): 
	$(CC) $(CFLAGS) -M $(.CFILES) > $(DEPENDFILE)

.SUFFIXES: .s .c .o .a

include Gasdepend
include $(DEPENDFILE)
data:
	$(foreach .ADIR_TMP, $(dir $(.AFILES)), make -C $(.ADIR_TMP);)

