#ifndef _MAP_H_
#define _MAP_H_

#define	HEIGHT_TILE_WIDTH	32
#define	HEIGHT_TILE_HEIGHT	32
#define	HEIGHT_UNIT_SIZE	1
#define	HEIGHT_TILE_COUNT	(HEIGHT_TILE_WIDTH * HEIGHT_TILE_HEIGHT)
#define	HEIGHT_TILE_SIZE	(HEIGHT_TILE_COUNT * HEIGHT_UNIT_SIZE)

#define	COLOUR_TILE_WIDTH	16
#define	COLOUR_TILE_HEIGHT	16
#define	COLOUR_UNIT_SIZE	2
#define	COLOUR_TILE_COUNT	(COLOUR_TILE_WIDTH * COLOUR_TILE_HEIGHT)
#define	COLOUR_TILE_SIZE	(COLOUR_TILE_COUNT * COLOUR_UNIT_SIZE)

#define	DAKAR_TILE_COUNT		128
#define	DAKAR_NUMBER_OF_TRACKS	12

#endif 