@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2
	.globl	Sound_Init
	.type	 Sound_Init,function
	.thumb_func
Sound_Init:
	push	{r7, lr}
	mov	r7, sp
.L2:
	pop	{r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Sound_Init,.Lfe1-Sound_Init
